theme: jekyll-theme-minimal
title: Han Spinner
description: "PhD Candidate<br/>
Biological and Biomedical Sciences<br/>
Harvard Medical School<br/>
<br/>
hspinner@g.harvard.edu"
logo: assets/images/my_head.png
