theme: jekyll-theme-minimal
title: Aviv Spinner
description: "Protein ML Research Fellow<br/>
AlignBio <br/>
Trained in Biological and Biomedical Sciences Harvard Medical School<br/>
Debora Marks Progeny<br/>
avivspinner@gmail.com"
logo: docs/assets/images/my_head_and_more.png
