theme: jekyll-theme-minimal
title: Aviv Spinner
description: "PhD Candidate<br/>
Biological and Biomedical Sciences<br/>
Harvard Medical School<br/>
<br/>
hspinner@g.harvard.edu"
logo: docs/assets/images/my_head_and_more.png
