theme: jekyll-theme-minimal
title: Aviv Spinner
description: "Protein ML Research Fellow<br/>
The Align Foundation <br/> <br/>
Boston, MA <br/> <br/>
Trained in Biological and Biomedical Sciences @ Harvard Medical School<br/> <br/>
Debora Marks Progeny<br/> <br/>
avivspinner@gmail.com"
logo: docs/assets/images/my_head_and_more.png
